from deepagents import DeepAgentState, create_deep_agent
from numpy import str_
from langchain_google_genai import ChatGoogleGenerativeAI
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from typing import Any, Dict
from parser import bin_to_dataframe_optimized
from langchain_core.tools import tool
import pandas as pd 
import numpy as np
import traceback
import message_information


load_dotenv()


class AgentState(DeepAgentState):
    message_dfs: Dict


class StructuredPandasQueryOutput(BaseModel):
    pandas_code: str = Field(..., description="The Pandas code generated by the agent")

    def to_dict(self) -> Dict[str, Any]:
        return {"pandas_code": self.pandas_code}


system_prompt = """ 
You are an expert in analyzing ArduPilot Logs. You will be given access to pre-processed telemetry data that has already been extracted from a .bin file.  
The data is stored in memory as a dictionary of Pandas DataFrames, keyed by message type (e.g., GPS, ATT, VIBE, CTUN).  
Users will ask you questions about the flight, and you will use the stored DataFrames to answer the questions.  

Your role is to analyze the user question and generate meaningful insights/reports/analytics from the data.

You can do the following:
1) Doing normal conversation with user
- Do greeting
- Do farewell
- Don't do small talks
- Answer if user is asking about your capabilities/potential.
- Do not answer questions unrelated to the overall goal of being a chatbot that can analyze ArduPilot Logs. Instead, tell the user that you are a chatbot that can analyze ArduPilot Logs and can't answer general questions. 
- If the user’s request is ambiguous, proactively ask clarifying questions before proceeding with analysis.

2) Analyzing the log file
- Analyze the log file to answer the user question.

Here is a simple general process that you can follow to answer the user question:
Step 0:(Optional) Ask clarifications
- Sometimes questions are vaugue or can be interperted in a lot of different ways when put in the context of a ArduPilot Log. 
<CRITICAL>
    - If you think the question is vaugue or can be interperted in a lot of different ways, ask clarifying questions before proceeding with analysis.
</CRITICAL>

Step 1: Select all relevant message types from the log file using the select_message_types_tool.
- select_message_types_tool:
    - Input:
        - question: str
            - The user question/request along with any relevant context from previous user questions and answers.

Step 2: Generate the Pandas Code.  
- generate_pandas_code_tool:
    - Input:
        - question: str
            - The user question/request along with any relevant context from previous user questions and answers.
        - message_types: str
            - A list of message types provided by the 'select_message_types_tool'. 
              Do not attempt to select message types manually.
    - Output:
        - Pandas code that analyzes the data to fulfill the data request.

Step 3: Execute the Pandas query: 
- pandas_executor_tool:  
    - Input: (pandas_code: str, message_types: str) 
        - The pandas_code generated by the generate_pandas_code_tool
        - The message_types should be the same list passed to the generate_pandas_code
    - Output: A pandas dataframe will be generated which has the answer
- If the pandas code fails to execute correct it and pass it into this tool again

Step 3b(Optional): Correct the Pandas code if it fails to execute
- pandas_code_correction_tool:  
    - Input:
        - pandas_code: str
            - The pandas code that failed to execute
        - error_message: str
            - The error message from the failed execution
    - Output:
        - corrected_pandas_code: str
            - The corrected pandas code that should execute without errors
- Do not use this tool unless pandas_executor_tool has failed to execute the code.
- Once you have the corrected pandas code, pass it into the pandas_executor_tool again with the same message_types

Step 4: Outputs the results
- summarize_results_tool:  
    - Output: Will output some of the results from the generated pandas dataframe

Step 5: Give the user the results:
- Summarize the results in a way that is easy to understand for the user. Always give context for the user like where did this data come from and what does it mean.

- Do not use this tool unless pandas_executor_tool has correctly executed
"""


@tool(
    description = """
    This tool will generate a potential list of message types that are relevant to answering the user question.

    - Input:
        - question: str
            - The user question/request along with any relevant context from previous user questions and answers.

    - Output:
        - Pandas code that analyzes the data to fulfill the data request.
    """
)
def select_message_types_tool(user_question: str) -> list[str]:
    llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature = 0.2)

    prompt = f""" 
You are analyzing an ArduPilot .bin log file. The log contains the following message types:
{message_types}

This is the user question that should be answered using the log data:
{user_question}


Consider the following when selecting messages:

* Sensor Lifecycle: Sensor messages (e.g., GPS, IMU, MAG, BARO, BAT, VIBE) may report zero, empty, or sentinel values during initialization, degradation, or failure. Only select messages that reliably record valid values for the relevant parameter. Sensor readings can drift or be incomplete during startup or recovery phases; plan selection logic accordingly.
* Vehicle Lifecycle: The vehicle passes through preflight, arming/takeoff, active flight, landing, and disarmed/shutdown phases. Prefer messages that provide meaningful information across the relevant phase(s). Avoid messages that exist only briefly unless the question specifically concerns that event. Values that seem anomalous or incomplete during preflight or post-flight are normal and should not lead to message exclusion unless relevant to the question.


Note: ArduPilot message types can be broadly categorized as follows:
- Sensors (e.g., GPS, IMU, MAG, BARO, BAT, VIBE) – record physical measurements.
- Flight/Attitude/Navigation (e.g., ATT, CTUN, POS, RATE, XKF*) – record vehicle motion and orientation.
- Commands, Modes, and Control (e.g., CMD, MODE, RCIN, PID*) – record vehicle state, commands sent, and control outputs.
- System info / Parameters / Metadata (e.g., PARM, VER, FMT) – record configuration, system state, and overall flight metadata.
- Errors / Warnings / Status messages (e.g., ERR, MSG) – record faults, warnings, or other important events.

Additionally, the following messages generally provide information throughout the flight and are useful for overall flight summary or timing:  
["ERR", "MSG", "MODE", "HEARTBEAT", "PARM", "VER", "FMT", "STAT", "STATS", "CMD", "MISSION"]

Guidelines for selecting relevant message types:

1. Consider Sensor and Vehicle Lifecycles:
   - Sensor Lifecycle: Sensor messages (e.g., GPS, IMU, MAG, BARO, BAT, VIBE) may report zero, empty, or sentinel values during initialization, degradation, or failure. Only select messages that reliably record valid values for the relevant parameter. Sensor readings can drift or be incomplete during startup or recovery phases; plan selection logic accordingly.
   - Vehicle Lifecycle: The vehicle passes through preflight, arming/takeoff, active flight, landing, and disarmed/shutdown phases. Prefer messages that provide meaningful information across the relevant phase(s). Avoid messages that exist only briefly unless the question specifically concerns that event. Values that seem anomalous or incomplete during preflight or post-flight are normal and should not lead to message exclusion unless relevant to the question.

2. If the question is about a specific flight parameter or sensor:
   - Select the message type(s) that record that parameter.
   - Consider whether the field is reliably populated and not just a placeholder (e.g., temperature may be 0 if no sensor).

3. If the question involves multiple parameters or subsystems:
   - Select all message types that contain relevant data.

4. If the question is about overall flight performance, summary metrics, or timing:
   - Select messages that cover the full flight, record vehicle state, arming/disarming, position, or timestamps.
   - Prefer messages from the list ["ERR", "MSG", "MODE", "HEARTBEAT", "PARM", "VER", "FMT", "STAT", "STATS", "CMD", "MISSION"] if they provide relevant information.
   - Avoid messages that exist only during specific events or short periods 

5. Always think in terms of ArduPilot telemetry and what each message type represents.
   - Do not select messages arbitrarily; select only those necessary to answer the question reliably.

Output format:
- Return only a Python list of message type names.
- Examples:
  - Single message type: ["GPS"]
  - Multiple message types: ["GPS", "ATT", "CTUN"]
- Do not include any extra text, explanation, or punctuation outside the list.

"""

    response = llm.invoke(prompt).content

    return response

