# from deepagents import DeepAgentState, create_deep_agent
# from numpy import str_
# from langchain_google_genai import ChatGoogleGenerativeAI
# from dotenv import load_dotenv
# from pydantic import BaseModel, Field
# from typing import Any, Dict
# from parser import bin_to_dataframe_optimized
# from langchain_core.tools import tool
# import pandas as pd 
# import numpy as np
# import traceback
# import message_information


# load_dotenv()

# class AgentState(DeepAgentState):
#     pass

# class StructuredPandasQueryOutput(BaseModel):
#     pandas_code: str = Field(..., description="The Pandas code generated by the agent")

#     def to_dict(self) -> Dict[str, Any]:
#         return {"pandas_code": self.pandas_code}


# message_types = """
# """

# message_dfs = bin_to_dataframe_optimized("1980-01-08 09-44-08.bin")

# result_df = ""

# system_prompt = """ 
# You are an expert in analyzing ArduPilot Logs. You will be given access to pre-processed telemetry data that has already been extracted from a .bin file.  
# The data is stored in memory as a dictionary of Pandas DataFrames, keyed by message type (e.g., GPS, ATT, VIBE, CTUN).  
# Users will ask you questions about the flight, and you will use the stored DataFrames to answer the questions.  

# Your role is to analyze the user question and generate meaningful insights/reports/analytics from the data.

# You can do the following:
# 1) Doing normal conversation with user
# - Do greeting
# - Do farewell
# - Don't do small talks
# - Answer if user is asking about your capabilities/potential.
# - Do not answer questions unrelated to the overall goal of being a chatbot that can analyze ArduPilot Logs. Instead, tell the user that you are a chatbot that can analyze ArduPilot Logs and can't answer general questions. 
# - If the user’s request is ambiguous, proactively ask clarifying questions before proceeding with analysis.

# 2) Analyzing the log file
# - Analyze the log file to answer the user question.

# Step 1: Select all relevant message types from the log file using the select_message_types_subagent.

# Step 2: Generate the Pandas Code.  

# Step 3: Execute the Pandas query: 

# Step 3b(Optional): Correct the Pandas code if it fails to execute

# Step 4: Outputs the results

# Step 5: Give the user the results:

# - Do not use this tool unless pandas_executor_tool has correctly executed
# """

# message_types = "\n".join(sorted(message_dfs.keys()))

# @tool(
#     description = """
#     This tool will generate a potential list of message types that are relevant to answering the user question.


#     """
# )
# def select_message_types_tool(user_question: str) -> list[str]:
#     llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature = 0.2)

#     prompt = f""" 
# You are analyzing an ArduPilot .bin log file. The log contains the following message types:
# {message_types}

# This is the user question that should be answered using the log data:
# {user_question}

# Consider the following when selecting messages:

# Output a list of messages to actually analyze

# """

#     response = llm.invoke(prompt).content

#     return response


# @tool(
#     description = """
#     This tool generates Pandas code to answers a user question using the provided message types.

#     """
# )
# def generate_pandas_code_tool(question: str, message_types: list[str]) -> str:

#     dfs_information = """"""

#     for msg_type in message_types: 
#         if msg_type in message_dfs:  
#             df = message_dfs[msg_type]
#             dfs_information += f"{msg_type}\n"
#             dfs_information += f"  {getattr(message_information, msg_type)}\n"
#             dfs_information += f"  dtypes: {df.dtypes.astype(str).to_dict()}\n"
#             if len(df) > 0:
#                 sample = df.head(1).to_csv(index=False).strip()
#             else:
#                 sample = "No data available in this dataframe"
            
#             dfs_information += f"  sample_data:\n{sample}\n"
#             dfs_information += "-" * 40 + "\n"  # separator lin

#     planner_prompt = f""" 
# You are an expert Python data analyst specializing in ArduPilot telemetry. Your goal is to create a step-by-step plan to answer a data request using provided Pandas DataFrame schemas. This plan will be used by another process to generate executable Python code.

# ---

# ### **Inputs**

# 1.  **Data Request:** 
# {question}

# 2.  **Available DataFrames:** 
# {dfs_information}

# ### **Your Final Output: A-by-Step Plan**

# """


#     llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature = 0.2)

#     pandas_plan = llm.invoke(planner_prompt).content

#     pandas_generator_prompt = f""" 
# # ROLE: Expert Python Writer

# You will be given the following data request to fufill:
# {question}

# The following dataframes to minipulate:
# {dfs_information}

# Python Plan Created to answer the question
# {pandas_plan}

# ---
# Your task is to write a complete, executable python code that follows the python plan.
# """
    

#     pandas_code = llm.with_structured_output(
#         StructuredPandasQueryOutput, include_raw = True
#     ).invoke(pandas_generator_prompt).get("parsed").to_dict()["pandas_code"]

#     return pandas_code 



# @tool(
#     description = "Given pandas code and a list of messages types to minipulate will execute the pandas code and store the result in a dataframe "
# )
# def pandas_executor_tool(pandas_code:str, message_types: list[str]):
#     ldict = { "pd": pd, "np": np,}

#     for msg_type in message_types: 
#         if msg_type in message_dfs:  
#             ldict[msg_type] = message_dfs[msg_type]

#     try:
#         # Execute user-provided code
#         exec(pandas_code, globals(), ldict)

#         # Retrieve the DataFrame from local dict
#         global result_df
#         result_df = ldict.get("result_df", None)

#         if result_df is None:
#             return "result_df was not generated"

#     except Exception:
#         # Log the exception
#         error_message = traceback.format_exc()
#         return f"Execution error: {error_message}"
        



# @tool(
#     description="Outputs some of the rows from the result_df "
# )
# def summarize_results_tool():
#     try:
#         temp = result_df.head(5).to_string(index=False)
#         return temp
#     except Exception as e:
#         return f"Error generating summary: {str(e)}"


# @tool(
#     description="""A tool that allows you to correct pandas code that has failed to execute. 
    
#     """
# )
# def pandas_code_correction_tool(pandas_code: str, error_message: str) -> str:
#     llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature = 0.2)

#     correction_prompt = f""" 
# Correct the following

# This is the pandas code that failed to execute:
# {pandas_code}

# This is the error message from the failed execution:
# {error_message}

# **REQUIREMENTS:**
# - Fix the error in the provided Python code, adhering strictly to the scope constraints above.
# - Do NOT create new sample data; operate on the provided `df`.
# - Return ONLY the corrected Python code as plain text.
# - Do not include any comments in the code.

# **ABSOLUTELY NO MARKDOWN FORMATTING ALLOWED**
# **DO NOT USE ```python or ``` or any code blocks**
# **DO NOT USE ANY BACKTICKS**
# **Your response must be ONLY raw Corrected Python code that can be directly executed with exec().**
# """
    
#     corrected_code = llm.invoke(correction_prompt).content

#     return corrected_code


# agent = create_deep_agent(
#     tools=[
#         generate_pandas_code_tool,
#         pandas_executor_tool,
#         summarize_results_tool,
#         select_message_types_tool,
#         pandas_code_correction_tool
#     ],
#     builtin_tools=["write_todos"],
#     instructions=system_prompt,
#     model=ChatGoogleGenerativeAI(model="gemini-2.5-flash-lite", temperature=0.2),
#     subagents=[
#     ],
#     state_schema=AgentState,
# ).with_config({"recursion_limit": 100})





from deepagents import DeepAgentState, create_deep_agent
from numpy import str_
from langchain_google_genai import ChatGoogleGenerativeAI
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from typing import Any, Dict
from parser import bin_to_dataframe_optimized
from langchain_core.tools import tool
import pandas as pd
import numpy as np
import traceback
import message_information


load_dotenv()


# ----------------------------
# State Schema (per agent/session)
# ----------------------------
class AgentState(DeepAgentState):
    message_dfs: Dict[str, pd.DataFrame] = {}
    result_df: pd.DataFrame | None = None


# ----------------------------
# Structured output class
# ----------------------------
class StructuredPandasQueryOutput(BaseModel):
    pandas_code: str = Field(..., description="The Pandas code generated by the agent")

    def to_dict(self) -> Dict[str, Any]:
        return {"pandas_code": self.pandas_code}


# ----------------------------
# Initialize once (not global state, just config)
# ----------------------------
system_prompt = """ 
You are an expert in analyzing ArduPilot Logs. You will be given access to pre-processed telemetry data...
(same as your prompt)
"""

# ----------------------------
# Tools
# ----------------------------

@tool
def select_message_types_tool(state: AgentState, user_question: str) -> list[str]:
    """ 
    Selects message types
    """
    llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.2)

    message_types = "\n".join(sorted(state.message_dfs.keys()))

    prompt = f"""
You are analyzing an ArduPilot .bin log file. The log contains the following message types:
{message_types}

This is the user question that should be answered using the log data:
{user_question}

Output a list of messages to actually analyze
"""

    response = llm.invoke(prompt).content
    return response


@tool
def generate_pandas_code_tool(state: AgentState, question: str, message_types: list[str]) -> str:
    """generates pandas code"""
    dfs_information = ""

    for msg_type in message_types:
        if msg_type in state.message_dfs:
            df = state.message_dfs[msg_type]
            dfs_information += f"{msg_type}\n"
            dfs_information += f"  {getattr(message_information, msg_type)}\n"
            dfs_information += f"  dtypes: {df.dtypes.astype(str).to_dict()}\n"
            if len(df) > 0:
                sample = df.head(1).to_csv(index=False).strip()
            else:
                sample = "No data available in this dataframe"

            dfs_information += f"  sample_data:\n{sample}\n"
            dfs_information += "-" * 40 + "\n"

    planner_prompt = f"""
You are an expert Python data analyst specializing in ArduPilot telemetry...
(question, dfs info, plan request)
"""

    llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.2)
    pandas_plan = llm.invoke(planner_prompt).content

    pandas_generator_prompt = f"""
# ROLE: Expert Python Writer
(question, dfs info, pandas_plan)
"""

    pandas_code = llm.with_structured_output(
        StructuredPandasQueryOutput, include_raw=True
    ).invoke(pandas_generator_prompt).get("parsed").to_dict()["pandas_code"]

    return pandas_code


@tool
def pandas_executor_tool(state: AgentState, pandas_code: str, message_types: list[str]):
    """executes pandas code """
    ldict = {"pd": pd, "np": np}

    for msg_type in message_types:
        if msg_type in state.message_dfs:
            ldict[msg_type] = state.message_dfs[msg_type]

    try:
        exec(pandas_code, globals(), ldict)
        state.result_df = ldict.get("result_df")

        if state.result_df is None:
            return "result_df was not generated"
        return "Execution successful"
    except Exception:
        return f"Execution error: {traceback.format_exc()}"


@tool
def summarize_results_tool(state: AgentState):
    """ summarize results tools""" 
    try:
        if state.result_df is None:
            return "No results available."
        return state.result_df.head(5).to_string(index=False)
    except Exception as e:
        return f"Error generating summary: {str(e)}"


@tool
def pandas_code_correction_tool(pandas_code: str, error_message: str) -> str:
    """ corrects pandas code"""
    llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=0.2)

    correction_prompt = f"""
Correct the following...

(pandas_code, error_message, requirements)
"""

    corrected_code = llm.invoke(correction_prompt).content
    return corrected_code

# ----------------------------
# Agent Factory
# ----------------------------
def make_agent(bin_file: str):
    """Create a new agent instance bound to one log file."""
    state = AgentState(message_dfs=bin_to_dataframe_optimized(bin_file))

    agent = create_deep_agent(
        tools=[
            generate_pandas_code_tool,
            pandas_executor_tool,
            summarize_results_tool,
            select_message_types_tool,
            pandas_code_correction_tool,
        ],
        builtin_tools=["write_todos"],
        instructions=system_prompt,
        model=ChatGoogleGenerativeAI(model="gemini-2.5-flash-lite", temperature=0.2),
        state_schema=AgentState,
    ).with_config({"recursion_limit": 100})

    return agent, state



agent,state = make_agent('1980-01-08 09-44-08.bin')

print("agent has been made")